import pytest
from customer_app.models import OrderModel
from deepdiff import DeepDiff
from freezegun import freeze_time
from rest_framework import status
from rest_framework.test import APIClient
from utils.enums import OrderStatusEnum


@pytest.fixture
def cooker_id() -> int:
    return 1


@pytest.mark.django_db
@pytest.mark.parametrize(
    "status_query_parameter,expected_data,expected_status_code,ok_value",
    [
        (
            {"status": OrderStatusEnum.PENDING},
            [
                {
                    "id": 9,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "pending",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 1, "firstname": "test", "lastname": "test"},
                    "delivery_man": None,
                    "sub_total": 0,
                    "service_fees": 0.0,
                    "total_amount": 2.4,
                },
                {
                    "id": 10,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "pending",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 1, "firstname": "test", "lastname": "test"},
                    "delivery_man": None,
                    "sub_total": 0,
                    "service_fees": 0.0,
                    "total_amount": 2.4,
                },
                {
                    "id": 1,
                    "address": {"id": 2, "postal_code": "91000", "town": "Evry"},
                    "items": [
                        {
                            "dish": {
                                "id": 1,
                                "category": "starter",
                                "country": "Cameroun",
                                "description": "Test",
                                "name": "Beignets haricots",
                                "price": 10.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 4,
                            },
                            "dish_quantity": 2,
                        },
                        {
                            "dish": {
                                "id": 2,
                                "category": "dish",
                                "country": "Congo",
                                "description": "Test",
                                "name": "Gombo porc riz",
                                "price": 13.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 4,
                            },
                            "dish_quantity": 1,
                        },
                        {
                            "drink": {
                                "id": 2,
                                "unit": "centiliters",
                                "country": "Cameroun",
                                "description": "Gingembre maison",
                                "name": "Gingembre",
                                "price": 5.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "capacity": 75,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 1,
                            },
                            "drink_quantity": 4,
                        },
                        {
                            "dish": {
                                "id": 11,
                                "category": "dessert",
                                "country": "Italie",
                                "description": "Tiramisu maison au spéculos",
                                "name": "Tiramisu spéculos",
                                "price": 5.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 1,
                            },
                            "dish_quantity": 1,
                        },
                    ],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-05-09T20:52:05.718117Z",
                    "scheduled_delivery_date": None,
                    "is_scheduled": False,
                    "status": "pending",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 3.19,
                    "delivery_fees_bonus": None,
                    "delivery_distance": 1390.0,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 4, "firstname": "toutii", "lastname": "N"},
                    "delivery_man": None,
                    "sub_total": 58.0,
                    "service_fees": 4.06,
                    "total_amount": 65.25,
                },
            ],
            200,
            True,
        ),
        (
            {"status": OrderStatusEnum.PROCESSING},
            [
                {
                    "id": 13,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "processing",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 1, "firstname": "test", "lastname": "test"},
                    "delivery_man": None,
                    "sub_total": 0,
                    "service_fees": 0.0,
                    "total_amount": 2.4,
                },
                {
                    "id": 7,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [
                        {
                            "dish": {
                                "id": 1,
                                "category": "starter",
                                "country": "Cameroun",
                                "description": "Test",
                                "name": "Beignets haricots",
                                "price": 10.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 4,
                            },
                            "dish_quantity": 2,
                        }
                    ],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-05-11T20:54:05.718117Z",
                    "scheduled_delivery_date": "2024-05-20T16:30:00Z",
                    "is_scheduled": False,
                    "status": "processing",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.7,
                    "delivery_fees_bonus": 1.4,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 4, "firstname": "toutii", "lastname": "N"},
                    "delivery_man": None,
                    "sub_total": 20.0,
                    "service_fees": 1.4,
                    "total_amount": 24.1,
                },
            ],
            200,
            True,
        ),
        (
            {"status": OrderStatusEnum.COMPLETED},
            [
                {
                    "id": 11,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 1, "firstname": "test", "lastname": "test"},
                    "delivery_man": None,
                    "sub_total": 0,
                    "service_fees": 0.0,
                    "total_amount": 2.4,
                },
                {
                    "id": 8,
                    "address": {"id": 3, "postal_code": "91540", "town": "Mennecy"},
                    "items": [
                        {
                            "dish": {
                                "id": 1,
                                "category": "starter",
                                "country": "Cameroun",
                                "description": "Test",
                                "name": "Beignets haricots",
                                "price": 10.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 4,
                            },
                            "dish_quantity": 2,
                        },
                        {
                            "dish": {
                                "id": 2,
                                "category": "dish",
                                "country": "Congo",
                                "description": "Test",
                                "name": "Gombo porc riz",
                                "price": 13.0,
                                "photo": "https://some-url.com",
                                "is_enabled": True,
                                "is_suitable_for_quick_delivery": False,
                                "is_suitable_for_scheduled_delivery": False,
                                "cooker": 4,
                            },
                            "dish_quantity": 1,
                        },
                    ],
                    "customer": {
                        "id": 1,
                        "stripe_id": "cus_QyZ76Ae0W5KeqP",
                        "lastname": "TEN",
                        "firstname": "Ben",
                    },
                    "created": "2024-05-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-05-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "processing_date": None,
                    "completed_date": None,
                    "delivery_in_progress_date": None,
                    "cancelled_date": None,
                    "delivered_date": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "cooker": {"id": 4, "firstname": "toutii", "lastname": "N"},
                    "delivery_man": None,
                    "sub_total": 33.0,
                    "service_fees": 2.31,
                    "total_amount": 37.71,
                },
            ],
            200,
            True,
        ),
        (
            {"status": "invalid"},
            [],
            200,
            True,
        ),
    ],
    ids=[
        "fetching orders in pending status",
        "fetching orders in processing status",
        "fetching orders in completed status",
        "fetching orders with invalid status",
    ],
)
@freeze_time("2024-12-11T02:53:05.718117Z")
def test_orders_list_success_with_no_filters(
    auth_headers: dict,
    client: APIClient,
    cooker_id: int,
    cookers_order_path: str,
    status_query_parameter: dict,
    expected_data: list[dict],
    expected_status_code: int,
    ok_value: bool,
) -> None:

    # we check that the cooker has some orders
    assert OrderModel.objects.filter(cooker__id=cooker_id).count() > 0

    # Then we list cooker orders
    response = client.get(
        cookers_order_path,
        follow=False,
        **auth_headers,
        data=status_query_parameter,
    )

    assert response.status_code == status.HTTP_200_OK
    assert response.json().get("ok") == ok_value
    assert response.json().get("status_code") == expected_status_code

    diff = DeepDiff(response.json().get("data"), expected_data, ignore_order=True)

    assert not diff
