default:
  cache:
    paths:
      - .docker_cache/

build-docker-image:
  script:
    - echo "Logging into Docker Hub..."
    - if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
        echo "DOCKER_USERNAME or DOCKER_PASSWORD is not set";
        exit 1;
      fi
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - echo "Building docker image..."
    - sudo docker compose -f reats/config/docker-compose.yaml up --build -d
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: build-docker-image


pre-commit:
  script:
    - echo "Running pre-commit hooks..."
    - docker exec -t django_app sh -c "pre-commit run -a"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: pre-commit


run-unit-tests:
  script:
    - echo "Running unit tests..."
    - docker exec -t django_app pytest -x -vv
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: run-unit-tests

stages:
  - build-docker-image
  - pre-commit
  - run-unit-tests
