repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--src-path", "source/"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--ignore", "F401"]  # TODO: Remove this error when will add more code in all apps!


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
          - django-extensions==3.2.3
          - django-phonenumber-field[phonenumberslite]==7.1.0
          - django-stubs==4.2.3
          - djangorestframework-stubs==3.14.2
          - djangorestframework==3.14.0
          - python-dotenv==1.0.0
          - psycopg2==2.9.6