# Generated by Django 4.1 on 2024-05-25 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliverModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        default="delivers/1/profile_pics/default-profile-pic.jpg",
                        max_length=512,
                    ),
                ),
                ("is_activated", models.BooleanField(default=False)),
                (
                    "delivery_vehicile",
                    models.CharField(
                        choices=[
                            ("bike", "bike"),
                            ("scooter", "scooter"),
                            ("car", "car"),
                        ],
                        default="bike",
                        max_length=7,
                    ),
                ),
                ("max_capacity_per_delivery", models.IntegerField()),
                ("delivery_postal_code", models.CharField(max_length=5)),
                ("delivery_town", models.CharField(max_length=100)),
                ("delivery_radius", models.IntegerField()),
                ("is_enabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "delivers",
            },
        ),
    ]
