# Generated by Django 4.1 on 2024-06-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivermodel",
            old_name="delivery_town",
            new_name="town",
        ),
        migrations.RemoveField(
            model_name="delivermodel",
            name="delivery_postal_code",
        ),
    ]
