# Generated by Django 4.1 on 2024-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivermodel",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
