# Generated by Django 4.1 on 2024-06-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_app", "0002_rename_delivery_town_delivermodel_town_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivermodel",
            name="max_capacity_per_delivery",
        ),
    ]
