# Generated by Django 4.1 on 2024-12-31 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="DrinkRatingModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.FloatField()),
                ("comment", models.TextField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drink_ratings",
                        to="core_app.customermodel",
                    ),
                ),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core_app.drinkmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drink_ratings",
                "unique_together": {("customer", "drink")},
            },
        ),
        migrations.CreateModel(
            name="DishRatingModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.FloatField()),
                ("comment", models.TextField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_ratings",
                        to="core_app.customermodel",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core_app.dishmodel",
                    ),
                ),
            ],
            options={
                "db_table": "dish_ratings",
                "unique_together": {("customer", "dish")},
            },
        ),
    ]
