# Generated by Django 4.1 on 2025-01-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0002_ordermodel_comment_ordermodel_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDishItemModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_quantity", models.IntegerField(null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app.dishmodel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes_items",
                        to="core_app.ordermodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_dishes_items",
            },
        ),
        migrations.CreateModel(
            name="OrderDrinkItemModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("drink_quantity", models.IntegerField(null=True)),
                (
                    "drink",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_app.drinkmodel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drinks_items",
                        to="core_app.ordermodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_drinks_items",
            },
        ),
        migrations.DeleteModel(
            name="OrderItemModel",
        ),
    ]
