# Generated by Django 4.1 on 2025-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0003_orderdishitemmodel_orderdrinkitemmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishratingmodel",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drinkratingmodel",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
