# Generated by Django 4.1 on 2025-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0004_alter_dishratingmodel_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customermodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
