# Generated by Django 4.1 on 2025-04-13 09:51

import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0005_cookermodel_is_deleted_customermodel_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("in_delivery", "in_delivery"),
                    ("cancelled_by_customer", "cancelled_by_customer"),
                    ("cancelled_by_cooker", "cancelled_by_cooker"),
                    ("delivered", "delivered"),
                ],
                default=utils.enums.OrderStatusEnum["DRAFT"],
                max_length=30,
            ),
        ),
    ]
