# Generated by Django 4.1 on 2026-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0006_alter_ordermodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="email",
            field=models.EmailField(default="-", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
