# Generated by Django 4.1 on 2026-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0006_alter_ordermodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name="cookermodel",
            index=models.Index(fields=["email"], name="cooker_email_idx"),
        ),
        migrations.AddIndex(
            model_name="cookermodel",
            index=models.Index(fields=["phone"], name="cooker_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="cookermodel",
            index=models.Index(fields=["is_deleted"], name="cooker_is_deleted_idx"),
        ),
        migrations.AddIndex(
            model_name="cookermodel",
            index=models.Index(fields=["is_online"], name="cooker_is_online_idx"),
        ),
        migrations.AddConstraint(
            model_name="cookermodel",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_cooker_email"),
        ),
    ]
