# Generated by Django 4.1 on 2026-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0007_cookermodel_email_cookermodel_cooker_email_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookermodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
