# Generated by Django 4.1 on 2026-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0007_cookermodel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishmodel",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="max_concurrent_orders",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="preparation_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
