# Generated by Django 4.1 on 2026-03-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0008_dishmodel_cost_dishmodel_max_concurrent_orders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergenModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "allergens",
            },
        ),
        migrations.CreateModel(
            name="IngredientModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "ingredients",
            },
        ),
        migrations.AlterField(
            model_name="orderdishitemmodel",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_order_items",
                to="core_app.dishmodel",
            ),
        ),
        migrations.CreateModel(
            name="NutritionalInfoModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("calories", models.IntegerField(null=True)),
                ("protein", models.IntegerField(null=True)),
                ("carbs", models.IntegerField(null=True)),
                ("fat", models.IntegerField(null=True)),
                (
                    "dish",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_info",
                        to="core_app.dishmodel",
                    ),
                ),
            ],
            options={
                "db_table": "nutritional_infos",
            },
        ),
        migrations.CreateModel(
            name="DishImageModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("s3_key", models.CharField(max_length=512)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core_app.dishmodel"
                    ),
                ),
            ],
            options={
                "db_table": "dish_images",
            },
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="allergens",
            field=models.ManyToManyField(blank=True, related_name="dishes", to="core_app.allergenmodel"),
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="ingredients",
            field=models.ManyToManyField(blank=True, related_name="dishes", to="core_app.ingredientmodel"),
        ),
    ]
