# Generated by Django 4.1 on 2026-03-01 17:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0008_dishmodel_cost_dishmodel_max_concurrent_orders_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dishmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector("name", config="simple", weight="A"),
                    "||",
                    django.contrib.postgres.search.SearchVector("description", config="simple", weight="B"),
                    django.contrib.postgres.search.SearchConfig("simple"),
                ),
                name="dish_name_desc_gin_idx",
            ),
        ),
    ]
