# Generated by Django 4.1 on 2026-03-03 10:43

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0009_dishmodel_dish_name_desc_gin_idx"),
    ]

    operations = [
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="dishmodel",
            name="dish_name_desc_gin_idx",
        ),
        migrations.AddIndex(
            model_name="dishmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="dish_name_trigram_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="dishmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="dish_desc_trigram_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
