# Generated by Django 4.1 on 2026-03-04 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0009_allergenmodel_ingredientmodel_and_more"),
        ("core_app", "0010_remove_dishmodel_dish_name_desc_gin_idx_and_more"),
    ]

    operations = []
