# Generated by Django 4.1 on 2026-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0010_remove_dishmodel_dish_name_desc_gin_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergenModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "allergens",
            },
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="allergens",
            field=models.ManyToManyField(blank=True, related_name="dishes", to="core_app.allergenmodel"),
        ),
    ]
