# Generated by Django 4.1 on 2026-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0011_allergendishmodel_dishmodel_allergens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergendishmodel",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
