# Generated by Django 4.1 on 2026-03-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0011_merge_20260304_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkmodel",
            name="allergens",
            field=models.ManyToManyField(blank=True, related_name="drinks", to="core_app.allergenmodel"),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="ingredients",
            field=models.ManyToManyField(blank=True, related_name="drinks", to="core_app.ingredientmodel"),
        ),
        migrations.CreateModel(
            name="DrinkNutritionalInfoModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("calories", models.IntegerField(null=True)),
                ("protein", models.IntegerField(null=True)),
                ("carbs", models.IntegerField(null=True)),
                ("fat", models.IntegerField(null=True)),
                (
                    "drink",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_info",
                        to="core_app.drinkmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drink_nutritional_infos",
            },
        ),
        migrations.CreateModel(
            name="DrinkImageModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("s3_key", models.CharField(max_length=512)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core_app.drinkmodel"
                    ),
                ),
            ],
            options={
                "db_table": "drink_images",
            },
        ),
    ]
