# Generated by Django 4.1 on 2026-03-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0012_ingredientdishmodel_dishmodel_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishImageModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("s3_key", models.CharField(max_length=512)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core_app.dishmodel"
                    ),
                ),
            ],
            options={
                "db_table": "dish_images",
            },
        ),
    ]
