# Generated by Django 4.1 on 2026-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0012_ingredientdishmodel_dishmodel_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientdishmodel",
            name="allergens",
            field=models.ManyToManyField(blank=True, related_name="ingredients", to="core_app.allergendishmodel"),
        ),
    ]
