# Generated by Django 4.1 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0012_add_db_index_to_allergen_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientDishModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_allergen", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ingredients_dishes",
            },
        ),
        migrations.RemoveField(
            model_name="dishmodel",
            name="allergens",
        ),
        migrations.DeleteModel(
            name="AllergenDishModel",
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="ingredients",
            field=models.ManyToManyField(blank=True, related_name="dishes", to="core_app.ingredientdishmodel"),
        ),
    ]
