# Generated by Django 4.1 on 2026-03-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0013_ingredientdishmodel_remove_dishmodel_allergens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishImageModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=512)),
                ("is_primary", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core_app.dishmodel"
                    ),
                ),
            ],
            options={
                "db_table": "dish_images",
                "ordering": ["position"],
            },
        ),
    ]
