# Generated by Django 4.1 on 2026-03-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0013_dishimagemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionalInfoDishModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("calories", models.IntegerField(null=True)),
                ("protein", models.IntegerField(null=True)),
                ("carbs", models.IntegerField(null=True)),
                ("fat", models.IntegerField(null=True)),
                (
                    "dish",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_dish_info",
                        to="core_app.dishmodel",
                    ),
                ),
            ],
            options={
                "db_table": "nutritional_dish_infos",
            },
        ),
    ]
