# Generated by Django 4.1 on 2026-03-16 14:49

from django.db import migrations


def migrate_photos(apps, schema_editor):
    DishModel = apps.get_model("core_app", "DishModel")
    DishImageModel = apps.get_model("core_app", "DishImageModel")

    for dish in DishModel.objects.exclude(photo="").exclude(photo__isnull=True):
        DishImageModel.objects.create(dish=dish, key=dish.photo, is_primary=True, position=0)


def reverse_migrate_photos(apps, schema_editor):
    DishImageModel = apps.get_model("core_app", "DishImageModel")
    DishImageModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0013_create_dishimage_model"),
    ]

    operations = [
        migrations.RunPython(migrate_photos, reverse_migrate_photos),
    ]
