# Generated by Django 4.1 on 2026-03-13 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0013_ingredientdishmodel_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishmodel",
            name="allergens",
        ),
    ]
