# Generated by Django 4.1 on 2026-03-16 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0015_migrate_dish_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishmodel",
            name="photo",
        ),
    ]
