# Generated by Django 4.1 on 2026-03-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0016_remove_dish_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishmodel",
            name="nutritional_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
