# Generated by Django 4.1 on 2026-03-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0016_remove_dish_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkImageModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=512)),
                ("is_primary", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core_app.drinkmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drink_images",
                "ordering": ["position"],
            },
        ),
    ]
