# Generated by Django 4.1 on 2026-03-23 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0018_migrate_drink_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drinkmodel",
            name="photo",
        ),
    ]
