# Generated by Django 4.1 on 2026-03-24 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0018_remove_dishmodel_nutritional_info_and_more"),
        ("core_app", "0019_remove_drink_photo"),
    ]

    operations = []
