# Generated by Django 4.1 on 2026-03-24 10:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0020_merge_20260324_0623"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="drinkmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="drink_name_trigram_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="drinkmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="drink_desc_trigram_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
