# Generated by Django 4.1 on 2026-03-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0021_drinkmodel_drink_name_trigram_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkNutritionalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("proteins", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("sugars", models.FloatField(blank=True, null=True)),
                ("fats", models.FloatField(blank=True, null=True)),
                ("saturated_fats", models.FloatField(blank=True, null=True)),
                ("fiber", models.FloatField(blank=True, null=True)),
                ("salt", models.FloatField(blank=True, null=True)),
                ("sodium", models.FloatField(blank=True, null=True)),
                (
                    "drink",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_info",
                        to="core_app.drinkmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drink_nutritional_info",
            },
        ),
    ]
