# Generated by Django 4.1 on 2026-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0022_drinknutritionalinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientDrinkModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_allergen", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ingredients_drinks",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="ingredients",
            field=models.ManyToManyField(blank=True, related_name="drinks", to="core_app.ingredientdrinkmodel"),
        ),
    ]
