# Generated by Django 4.1 on 2026-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0023_ingredientdrinkmodel_drinkmodel_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishmodel",
            name="description",
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="drinkmodel",
            name="description",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
