# Generated by Django 4.1 on 2026-04-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0024_alter_dishmodel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishmodel",
            name="description",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
