# Generated by Django 4.1 on 2026-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0024_alter_dishmodel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinkmodel",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dishmodel",
            name="description",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
