# Generated by Django 5.2 on 2026-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0025_alter_dishmodel_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dishratingmodel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="drinkratingmodel",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dishratingmodel",
            constraint=models.UniqueConstraint(fields=("customer", "dish"), name="unique_customer_dish_rating"),
        ),
        migrations.AddConstraint(
            model_name="drinkratingmodel",
            constraint=models.UniqueConstraint(fields=("customer", "drink"), name="unique_customer_drink_rating"),
        ),
    ]
