# Generated by Django 5.2 on 2026-04-29 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0025_drinkmodel_cost_alter_dishmodel_description"),
        ("core_app", "0026_alter_dishratingmodel_unique_together_and_more"),
    ]

    operations = []
