# Generated by Django 5.2 on 2026-05-21 10:28

import utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0028_alter_ordermodel_delivery_fees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="delivered_date",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="delivery_in_progress_date",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="processing_date",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="accepted_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="cancelled_by",
            field=models.CharField(
                choices=[("cooker", "cooker"), ("customer", "customer"), ("system", "system")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivering_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="preparing_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="ready_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("preparing", "preparing"),
                    ("ready", "ready"),
                    ("delivering", "delivering"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("not_accepted", "not_accepted"),
                ],
                default=utils.enums.OrderStatusEnum["DRAFT"],
                max_length=30,
            ),
        ),
    ]
