# Generated by Django 5.2 on 2026-07-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0031_cookerfcmdevicemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverFCMDeviceModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")], max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deliver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to="core_app.delivermodel",
                    ),
                ),
            ],
            options={
                "db_table": "deliver_fcm_devices",
            },
        ),
    ]
