# Generated by Django 4.1 on 2023-08-13 18:32

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookerModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="FR", unique=True
                    ),
                ),
                (
                    "postal_code",
                    models.IntegerField(
                        validators=[
                            django.core.validators.RegexValidator(regex="[0-9]{5}")
                        ]
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="[0-9]{14}")
                        ],
                    ),
                ),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.IntegerField()),
                ("town", models.CharField(max_length=100)),
                ("address_complement", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "cookers",
            },
        ),
    ]
