# Generated by Django 4.1 on 2023-08-15 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookermodel",
            name="phone",
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name="cookermodel",
            name="postal_code",
            field=models.CharField(
                max_length=5,
                validators=[django.core.validators.RegexValidator(regex="[0-9]{5}")],
            ),
        ),
        migrations.AlterField(
            model_name="cookermodel",
            name="street_number",
            field=models.CharField(max_length=10),
        ),
    ]
