# Generated by Django 4.1 on 2023-09-02 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0005_dishmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishmodel",
            name="photo",
            field=models.URLField(
                max_length=512,
                validators=[django.core.validators.URLValidator(schemes=["file"])],
            ),
        ),
    ]
