# Generated by Django 4.1 on 2024-06-01 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookerModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(regex="[0-9]{5}")
                        ],
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="[0-9]{14}")
                        ],
                    ),
                ),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("town", models.CharField(max_length=100)),
                ("address_complement", models.CharField(max_length=512, null=True)),
                (
                    "photo",
                    models.CharField(
                        default="cookers/1/profile_pics/default-profile-pic.jpg",
                        max_length=512,
                    ),
                ),
                ("max_order_number", models.IntegerField(default=10)),
                ("is_online", models.BooleanField(default=False)),
                ("is_activated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "cookers",
            },
        ),
        migrations.CreateModel(
            name="DrinkModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "unit",
                    models.CharField(
                        choices=[("liter", "liter"), ("centiliters", "centiliters")],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=512, null=True)),
                ("name", models.CharField(max_length=128)),
                ("price", models.FloatField()),
                ("photo", models.CharField(max_length=512)),
                ("is_enabled", models.BooleanField(default=True)),
                ("capacity", models.IntegerField()),
                (
                    "cooker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.cookermodel",
                    ),
                ),
            ],
            options={
                "db_table": "drinks",
            },
        ),
        migrations.CreateModel(
            name="DishModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("starter", "starter"),
                            ("dish", "dish"),
                            ("dessert", "dessert"),
                        ],
                        max_length=9,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=512, null=True)),
                ("name", models.CharField(max_length=128)),
                ("price", models.FloatField()),
                ("photo", models.CharField(max_length=512)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "cooker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.cookermodel",
                    ),
                ),
            ],
            options={
                "db_table": "dishes",
            },
        ),
    ]
