# Generated by Django 4.1 on 2024-02-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenericUser",
        ),
    ]
