# Generated by Django 4.1 on 2024-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishmodel",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("now", "now"),
                    ("scheduled", "scheduled"),
                    ("both_now_and_scheduled", "both_now_and_scheduled"),
                ],
                default="both_now_and_scheduled",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("now", "now"),
                    ("scheduled", "scheduled"),
                    ("both_now_and_scheduled", "both_now_and_scheduled"),
                ],
                default="both_now_and_scheduled",
                max_length=30,
            ),
        ),
    ]
