# Generated by Django 4.1 on 2024-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0002_dishmodel_delivery_mode_drinkmodel_delivery_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishmodel",
            name="delivery_mode",
        ),
        migrations.RemoveField(
            model_name="drinkmodel",
            name="delivery_mode",
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="is_suitable_for_quick_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dishmodel",
            name="is_suitable_for_scheduled_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="is_suitable_for_quick_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="drinkmodel",
            name="is_suitable_for_scheduled_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
