# Generated by Django 4.1 on 2023-09-02 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cooker_app",
            "0003_remove_cookermodel_email_remove_cookermodel_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookermodel",
            name="phone",
            field=models.CharField(
                max_length=17,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
