# Generated by Django 4.1 on 2024-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0003_remove_dishmodel_delivery_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="acceptance_rate",
            field=models.FloatField(default=100.0),
        ),
    ]
