# Generated by Django 4.1 on 2024-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0004_cookermodel_acceptance_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="last_acceptance_rate_update_date",
            field=models.DateTimeField(null=True),
        ),
    ]
