# Generated by Django 4.1 on 2023-09-02 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0004_alter_cookermodel_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("starter", "starter"),
                            ("main_dish", "main_dish"),
                            ("dessert", "dessert"),
                        ],
                        max_length=9,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=512, null=True)),
                ("name", models.CharField(max_length=128)),
                ("price", models.FloatField()),
                ("photo", models.URLField(max_length=512)),
                (
                    "cooker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.cookermodel",
                    ),
                ),
            ],
            options={
                "db_table": "dishes",
            },
        ),
    ]
