# Generated by Django 4.1 on 2023-09-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0006_alter_dishmodel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishmodel",
            name="photo",
            field=models.CharField(max_length=512),
        ),
    ]
