# Generated by Django 4.1 on 2023-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0007_alter_dishmodel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="photo",
            field=models.URLField(null=True),
        ),
    ]
