# Generated by Django 4.1 on 2023-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0009_alter_dishmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishmodel",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
