# Generated by Django 4.1 on 2023-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0010_dishmodel_is_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookermodel",
            name="photo",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
