# Generated by Django 4.1 on 2023-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0011_alter_cookermodel_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="max_order_number",
            field=models.IntegerField(default=10),
        ),
    ]
