# Generated by Django 4.1 on 2023-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0012_cookermodel_max_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookermodel",
            name="photo",
            field=models.CharField(
                default="cookers/1/profile_pics/default-profile-pic.jpg", max_length=512
            ),
        ),
    ]
