# Generated by Django 4.1 on 2023-12-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0014_drinkmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
