# Generated by Django 4.1 on 2023-12-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0015_cookermodel_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookermodel",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
