# pull official base image
FROM python:3.9-alpine

# set work directory
WORKDIR /usr/src/app/reats

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# get some useful python lib for dev
RUN apk update \
    && apk add python3-dev postgresql-dev gcc musl-dev

# install dependencies
RUN pip3 install --upgrade pip
RUN pip3 install pipenv
COPY ./Pipfile* ./
RUN pipenv lock --requirements > requirements.txt
RUN pip3 install -r requirements.txt

# copy project
COPY ./reats /usr/src/app/reats

# Expose port
EXPOSE 8000
EXPOSE 8001

# copy env files
COPY ./reats/.env-dev-tpl ./.env-dev

# copy entrypoint
COPY ./reats/entrypoint.sh .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/reats/entrypoint.sh"]