# Generated by Django 4.1 on 2024-06-01 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cooker_app", "0001_initial"),
        ("delivery_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("town", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=5)),
                ("address_complement", models.CharField(max_length=512, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        default="customers/1/profile_pics/default-profile-pic.jpg",
                        max_length=512,
                    ),
                ),
                ("is_activated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("delivery_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("cancelled_by_customer", "cancelled_by_customer"),
                            ("cancelled_by_cooker", "cancelled_by_cooker"),
                            ("delivered", "delivered"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer_app.addressmodel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer_app.customermodel",
                    ),
                ),
                (
                    "delivery_man",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery_app.delivermodel",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_quantity", models.IntegerField(null=True)),
                ("drink_quantity", models.IntegerField(null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.dishmodel",
                    ),
                ),
                (
                    "drink",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.drinkmodel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customer_app.ordermodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="customer_app.customermodel",
            ),
        ),
    ]
