# Generated by Django 4.1 on 2024-02-10 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        default="customers/1/profile_pics/default-profile-pic.jpg",
                        max_length=512,
                    ),
                ),
                ("is_activated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customers",
            },
        ),
    ]
