# Generated by Django 4.1 on 2024-08-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_planning",
            field=models.CharField(
                choices=[("asap", "asap"), ("scheduled", "scheduled")],
                default="asap",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer_app.addressmodel",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="scheduled_delivery_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("cancelled_by_customer", "cancelled_by_customer"),
                    ("cancelled_by_cooker", "cancelled_by_cooker"),
                    ("delivered", "delivered"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
