# Generated by Django 4.1 on 2024-02-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("town", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=5)),
                ("address_complement", models.CharField(max_length=512)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customer_app.customermodel",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
            },
        ),
    ]
