# Generated by Django 4.1 on 2024-06-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="deliveryFees",
            new_name="delivery_fees",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="deliveryFeesBonus",
            new_name="delivery_fees_bonus",
        ),
    ]
