# Generated by Django 4.1 on 2024-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0002_ordermodel_delivery_planning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="delivery_fees",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="delivery_fees_bonus",
            field=models.FloatField(null=True),
        ),
    ]
