# Generated by Django 4.1 on 2024-02-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0002_addressmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressmodel",
            name="address_complement",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
