# Generated by Django 4.1 on 2024-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0002_rename_deliveryfees_ordermodel_delivery_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_cancelled_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_completed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_delivered_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_in_progress_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_processing_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
