# Generated by Django 4.1 on 2024-08-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0003_alter_ordermodel_delivery_fees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="delivery_planning",
        ),
    ]
