# Generated by Django 4.1 on 2024-06-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0003_ordermodel_delivery_cancelled_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="delivery_cancelled_date",
            new_name="cancelled_date",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="delivery_completed_date",
            new_name="completed_date",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="delivery_delivered_date",
            new_name="delivered_date",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="delivery_processing_date",
            new_name="processing_date",
        ),
    ]
