# Generated by Django 4.1 on 2024-05-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0003_alter_cookermodel_address_complement"),
        ("customer_app", "0003_alter_addressmodel_address_complement"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("delivery_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("cancelled_by_customer", "cancelled_by_customer"),
                            ("cancelled_by_cooker", "cancelled_by_cooker"),
                            ("delivered", "delivered"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer_app.addressmodel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer_app.customermodel",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_quantity", models.IntegerField()),
                ("drink_quantity", models.IntegerField(null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.dishmodel",
                    ),
                ),
                (
                    "drink",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooker_app.drinkmodel",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customer_app.ordermodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
    ]
