# Generated by Django 4.1 on 2024-08-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0004_remove_ordermodel_delivery_planning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer_app.addressmodel",
            ),
        ),
    ]
