# Generated by Django 4.1 on 2024-06-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_app",
            "0004_rename_delivery_cancelled_date_ordermodel_cancelled_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="delivery_date",
            new_name="scheduled_delivery_date",
        ),
    ]
