# Generated by Django 4.1 on 2024-05-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0003_alter_cookermodel_address_complement"),
        ("customer_app", "0004_ordermodel_orderitemmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemmodel",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cooker_app.dishmodel",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="dish_quantity",
            field=models.IntegerField(null=True),
        ),
    ]
