# Generated by Django 4.1 on 2024-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_app",
            "0005_rename_delivery_date_ordermodel_scheduled_delivery_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_distance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="delivery_initial_distance",
            field=models.FloatField(null=True),
        ),
    ]
