# Generated by Django 4.1 on 2024-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0005_alter_ordermodel_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="paid_date",
            field=models.DateTimeField(null=True),
        ),
    ]
