# Generated by Django 4.1 on 2024-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0005_alter_orderitemmodel_dish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
