# Generated by Django 4.1 on 2024-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0006_ordermodel_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="stripe_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
