# Generated by Django 4.1 on 2024-10-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0008_ordermodel_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="stripe_payment_intent_secret",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
