# Generated by Django 4.1 on 2024-12-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooker_app", "0003_remove_dishmodel_delivery_mode_and_more"),
        ("customer_app", "0009_ordermodel_stripe_payment_intent_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="cooker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cooker_app.cookermodel",
            ),
        ),
    ]
