import pytest
from core_app.models import OrderModel
from deepdiff import DeepDiff
from freezegun import freeze_time
from rest_framework import status
from rest_framework.test import APIClient
from utils.enums import OrderStatusEnum, SuccessMessageEnum


@pytest.fixture
def customer_id() -> int:
    return 1


@pytest.fixture
def expected_data() -> list[dict]:
    return [
        {
            "id": 17,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "cancelled",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": "customer",
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 12,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "cancelled",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": "cooker",
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 11,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 14,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 15,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 16,
            "dishes_items": [],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-12-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-12-17T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 1,
                "firstname": "test",
                "lastname": "test",
                "email": "test@gmail.com",
                "acceptance_rate": 100.0,
            },
            "delivery_man": None,
            "sub_total": 0.0,
            "service_fees": 0.0,
            "total_amount": 2.4,
        },
        {
            "id": 4,
            "dishes_items": [
                {
                    "dish": {
                        "id": 1,
                        "ratings": [],
                        "category": "starter",
                        "country": "Cameroun",
                        "description": "Test",
                        "name": "Beignets haricots",
                        "price": 10.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "email": "test4@gmail.com",
                            "acceptance_rate": 100.0,
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 2,
                },
                {
                    "dish": {
                        "id": 2,
                        "ratings": [],
                        "category": "dish",
                        "country": "Congo",
                        "description": "Test",
                        "name": "Gombo porc riz",
                        "price": 13.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 1,
                },
            ],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-04-02T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-04-10T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": "2024-03-02T21:15:05.718117Z",
            "preparing_date": None,
            "ready_date": "2024-03-02T21:25:05.718117Z",
            "delivering_date": "2024-03-02T21:33:05.718117Z",
            "completed_date": "2024-03-02T21:45:05.718117Z",
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 3.7,
            "delivery_fees_bonus": 1.3,
            "delivery_distance": 2.5,
            "delivery_initial_distance": 1.5,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 4,
                "firstname": "toutii",
                "lastname": "N",
                "acceptance_rate": 100.0,
                "email": "test4@gmail.com",
            },
            "delivery_man": 1,
            "sub_total": 33.0,
            "service_fees": 2.31,
            "total_amount": 39.01,
        },
        {
            "id": 3,
            "dishes_items": [
                {
                    "dish": {
                        "id": 1,
                        "ratings": [],
                        "category": "starter",
                        "country": "Cameroun",
                        "description": "Test",
                        "name": "Beignets haricots",
                        "price": 10.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 2,
                },
                {
                    "dish": {
                        "id": 2,
                        "ratings": [],
                        "category": "dish",
                        "country": "Congo",
                        "description": "Test",
                        "name": "Gombo porc riz",
                        "price": 13.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 1,
                },
                {
                    "dish": {
                        "id": 11,
                        "ratings": [],
                        "category": "dessert",
                        "country": "Italie",
                        "description": "Tiramisu maison au spéculos",
                        "name": "Tiramisu spéculos",
                        "price": 5.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 1,
                            "firstname": "test",
                            "lastname": "test",
                            "acceptance_rate": 100.0,
                            "email": "test@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 1,
                },
            ],
            "drinks_items": [
                {
                    "drink": {
                        "id": 2,
                        "ratings": [],
                        "unit": "centiliters",
                        "country": "Cameroun",
                        "description": "Gingembre maison",
                        "name": "Gingembre",
                        "price": 5.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "capacity": 75,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 1,
                            "firstname": "test",
                            "lastname": "test",
                            "acceptance_rate": 100.0,
                            "email": "test@gmail.com",
                        },
                        "nutritional_info": {},
                        "ingredients": [],
                    },
                    "drink_quantity": 4,
                }
            ],
            "address": {
                "id": 2,
                "street_name": "rue des Mazières",
                "street_number": "13",
                "town": "Evry",
                "postal_code": "91000",
                "address_complement": None,
                "customer": 1,
            },
            "created": "2024-03-02T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-03-10T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": "2024-03-02T21:15:05.718117Z",
            "preparing_date": None,
            "ready_date": "2024-03-02T21:25:05.718117Z",
            "delivering_date": "2024-03-02T21:33:05.718117Z",
            "completed_date": "2024-03-02T21:45:05.718117Z",
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 3.2,
            "delivery_fees_bonus": 1.5,
            "delivery_distance": 3.0,
            "delivery_initial_distance": 2.0,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 4,
                "firstname": "toutii",
                "lastname": "N",
                "acceptance_rate": 100.0,
                "email": "test4@gmail.com",
            },
            "delivery_man": 1,
            "sub_total": 58.0,
            "service_fees": 4.06,
            "total_amount": 65.26,
        },
        {
            "id": 8,
            "dishes_items": [
                {
                    "dish": {
                        "id": 1,
                        "ratings": [],
                        "category": "starter",
                        "country": "Cameroun",
                        "description": "Test",
                        "name": "Beignets haricots",
                        "price": 10.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 2,
                },
                {
                    "dish": {
                        "id": 2,
                        "ratings": [],
                        "category": "dish",
                        "country": "Congo",
                        "description": "Test",
                        "name": "Gombo porc riz",
                        "price": 13.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 1,
                },
            ],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-05-11T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-05-17T16:30:00Z",
            "is_scheduled": False,
            "status": "completed",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": None,
            "delivery_fees": 2.4,
            "delivery_fees_bonus": 1.1,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 4,
                "firstname": "toutii",
                "lastname": "N",
                "acceptance_rate": 100.0,
                "email": "test4@gmail.com",
            },
            "delivery_man": None,
            "sub_total": 33.0,
            "service_fees": 2.31,
            "total_amount": 37.71,
        },
        {
            "id": 5,
            "dishes_items": [
                {
                    "dish": {
                        "id": 1,
                        "ratings": [],
                        "category": "starter",
                        "country": "Cameroun",
                        "description": "Test",
                        "name": "Beignets haricots",
                        "price": 10.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 2,
                },
                {
                    "dish": {
                        "id": 2,
                        "ratings": [],
                        "category": "dish",
                        "country": "Congo",
                        "description": "Test",
                        "name": "Gombo porc riz",
                        "price": 13.0,
                        "image": "https://some-url.com",
                        "is_enabled": True,
                        "is_suitable_for_quick_delivery": False,
                        "is_suitable_for_scheduled_delivery": False,
                        "cooker": {
                            "id": 4,
                            "firstname": "toutii",
                            "lastname": "N",
                            "acceptance_rate": 100.0,
                            "email": "test4@gmail.com",
                        },
                        "ingredients": [],
                        "nutritional_info": {},
                    },
                    "dish_quantity": 1,
                },
            ],
            "drinks_items": [],
            "address": {
                "id": 3,
                "street_name": "Rue Jean Cocteau",
                "street_number": "2",
                "town": "Mennecy",
                "postal_code": "91540",
                "address_complement": None,
                "customer": 2,
            },
            "created": "2024-02-02T20:53:05.718117Z",
            "scheduled_delivery_date": "2024-02-10T16:30:00Z",
            "is_scheduled": False,
            "status": "cancelled",
            "accepted_date": None,
            "preparing_date": None,
            "ready_date": None,
            "delivering_date": None,
            "completed_date": None,
            "cancelled_date": None,
            "cancelled_by": "cooker",
            "delivery_fees": 4.1,
            "delivery_fees_bonus": 1.2,
            "delivery_distance": None,
            "delivery_initial_distance": None,
            "paid_date": None,
            "stripe_payment_intent_id": None,
            "stripe_payment_intent_secret": None,
            "rating": 0.0,
            "comment": None,
            "cooker": {
                "id": 4,
                "firstname": "toutii",
                "lastname": "N",
                "acceptance_rate": 100.0,
                "email": "test4@gmail.com",
            },
            "delivery_man": None,
            "sub_total": 33.0,
            "service_fees": 2.31,
            "total_amount": 39.41,
        },
    ]


@pytest.mark.django_db
def test_orders_history_list_success_for_customers(
    auth_headers: dict,
    client: APIClient,
    customer_id: int,
    customer_order_history_path: str,
    expected_data: list[dict],
) -> None:
    # we check that the customer has some orders
    assert OrderModel.objects.filter(customer__id=customer_id).count() > 0

    # Then we list customer orders history
    response = client.get(
        customer_order_history_path,
        follow=False,
        **auth_headers,
    )
    assert response.status_code == status.HTTP_200_OK
    diff = DeepDiff(response.json().get("data").get("results"), expected_data, ignore_order=True)

    assert not diff


@pytest.mark.django_db
@pytest.mark.parametrize(
    "order_status",
    [
        OrderStatusEnum.CANCELLED,
        OrderStatusEnum.CANCELLED,
        OrderStatusEnum.COMPLETED,
    ],
    ids=[
        "fetching orders in cancelled by cooker status",
        "fetching orders in cancelled by customer status",
        "fetching orders in delivered status",
    ],
)
@freeze_time("2024-12-11T02:53:05.718117Z")
def test_orders_list_success_with_order_status_filter(
    auth_headers: dict,
    client: APIClient,
    customer_id: int,
    customer_order_history_path: str,
    order_status: OrderStatusEnum,
) -> None:
    # we check that the cooker has some orders
    assert OrderModel.objects.filter(customer__id=customer_id).count() > 0

    # Then we list cooker orders
    response = client.get(
        customer_order_history_path,
        follow=False,
        **auth_headers,
        data={"status": order_status},
    )

    assert response.status_code == status.HTTP_200_OK
    assert response.json().get("success") is True
    assert response.json().get("message") == SuccessMessageEnum.OPERATION_SUCCESSFUL.value

    for order_item in response.json().get("data").get("results"):
        assert order_item.get("status") == order_status.value


@pytest.mark.django_db
@freeze_time("2024-12-11T02:53:05.718117Z")
def test_orders_list_success_with_dates_filter_when_some_orders_exist(
    auth_headers: dict,
    client: APIClient,
    customer_id: int,
    customer_order_history_path: str,
) -> None:
    # we check that the cooker has some orders
    assert OrderModel.objects.filter(customer__id=customer_id).count() > 0

    # Then we list cooker orders
    response = client.get(
        customer_order_history_path,
        follow=False,
        **auth_headers,
        data={
            "start_date": "2024-12-10T00:00:00.000Z",
            "end_date": "2024-12-12T00:00:00.000Z",
        },
    )

    assert response.status_code == status.HTTP_200_OK
    assert response.json().get("success") is True
    assert response.json().get("message") == SuccessMessageEnum.OPERATION_SUCCESSFUL.value
    assert len(response.json().get("data").get("results")) > 0


@pytest.mark.django_db
@freeze_time("2024-12-11T02:53:05.718117Z")
def test_orders_list_success_with_dates_filter_when_no_orders_exist(
    auth_headers: dict,
    client: APIClient,
    customer_id: int,
    customer_order_history_path: str,
) -> None:
    # we check that the cooker has some orders
    assert OrderModel.objects.filter(customer__id=customer_id).count() > 0

    # Then we list cooker orders
    response = client.get(
        customer_order_history_path,
        follow=False,
        **auth_headers,
        data={
            "start_date": "2024-11-10T00:00:00.000Z",
            "end_date": "2024-11-12T00:00:00.000Z",
        },
    )

    assert response.status_code == status.HTTP_200_OK
    assert response.json().get("success") is True
    assert response.json().get("message") == SuccessMessageEnum.OPERATION_SUCCESSFUL.value
    assert len(response.json().get("data").get("results")) == 0


@pytest.mark.django_db
@pytest.mark.parametrize(
    "order_status, start_date, end_date, expected_data",
    [
        (
            OrderStatusEnum.CANCELLED,
            "2024-12-10T00:00:00.000Z",
            "2024-12-12T00:00:00.000Z",
            [
                {
                    "id": 12,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "cancelled",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": "cooker",
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "acceptance_rate": 100.0,
                        "firstname": "test",
                        "id": 1,
                        "lastname": "test",
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
                {
                    "id": 17,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "cancelled",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": "customer",
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
            ],
        ),
        (
            OrderStatusEnum.CANCELLED,
            "2024-12-10T00:00:00.000Z",
            "2024-12-12T00:00:00.000Z",
            [
                {
                    "id": 12,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "cancelled",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": "cooker",
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "acceptance_rate": 100.0,
                        "firstname": "test",
                        "id": 1,
                        "lastname": "test",
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
                {
                    "id": 17,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "cancelled",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": "customer",
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
            ],
        ),
        (
            OrderStatusEnum.COMPLETED,
            "2024-12-10T00:00:00.000Z",
            "2024-12-12T00:00:00.000Z",
            [
                {
                    "id": 14,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
                {
                    "id": 15,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
                {
                    "id": 16,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
                {
                    "id": 11,
                    "dishes_items": [],
                    "drinks_items": [],
                    "address": {
                        "id": 3,
                        "street_name": "Rue Jean Cocteau",
                        "street_number": "2",
                        "town": "Mennecy",
                        "postal_code": "91540",
                        "address_complement": None,
                        "customer": 2,
                    },
                    "created": "2024-12-11T20:53:05.718117Z",
                    "scheduled_delivery_date": "2024-12-17T16:30:00Z",
                    "is_scheduled": False,
                    "status": "completed",
                    "accepted_date": None,
                    "preparing_date": None,
                    "ready_date": None,
                    "delivering_date": None,
                    "completed_date": None,
                    "cancelled_date": None,
                    "cancelled_by": None,
                    "delivery_fees": 2.4,
                    "delivery_fees_bonus": 1.1,
                    "delivery_distance": None,
                    "delivery_initial_distance": None,
                    "paid_date": None,
                    "stripe_payment_intent_id": None,
                    "stripe_payment_intent_secret": None,
                    "cooker": {
                        "id": 1,
                        "firstname": "test",
                        "lastname": "test",
                        "acceptance_rate": 100.0,
                        "email": "test@gmail.com",
                    },
                    "delivery_man": None,
                    "sub_total": 0.0,
                    "service_fees": 0.0,
                    "rating": 0.0,
                    "comment": None,
                    "total_amount": 2.4,
                },
            ],
        ),
    ],
    ids=[
        "fetching orders in cancelled by cooker status",
        "fetching orders in cancelled by customer status",
        "fetching orders in delivered status",
    ],
)
@freeze_time("2024-12-23T02:53:05.718117Z")
def test_orders_list_success_with_multiple_filters(
    auth_headers: dict,
    client: APIClient,
    customer_id: int,
    customer_order_history_path: str,
    order_status: OrderStatusEnum,
    start_date: str,
    end_date: str,
    expected_data: list[dict],
) -> None:
    # we check that the cooker has some orders
    assert OrderModel.objects.filter(customer__id=customer_id).count() > 0

    # Then we list cooker orders
    response = client.get(
        customer_order_history_path,
        follow=False,
        **auth_headers,
        data={
            "status": order_status,
            "start_date": start_date,
            "end_date": end_date,
        },
    )

    assert response.status_code == status.HTTP_200_OK
    assert response.json().get("success") is True
    assert response.json().get("message") == SuccessMessageEnum.OPERATION_SUCCESSFUL.value

    diff = DeepDiff(response.json().get("data").get("results"), expected_data, ignore_order=True)

    assert not diff
