version: "3.7"

services:
  web:
    build:
      context: ../..
      dockerfile: reats/config/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../customer_app:/usr/src/app/reats/customer_app/
      - ../cooker_app:/usr/src/app/reats/cooker_app/
      - ../custom_renderers:/usr/src/app/reats/custom_renderers/
      - ../delivery_app:/usr/src/app/reats/delivery_app/
      - ../source:/usr/src/app/reats/source/
      - ../tests:/usr/src/app/reats/tests/
      - ../utils:/usr/src/app/reats/utils/
    container_name: django_app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    env_file:
      - .env
    container_name: postgres_db

volumes:
  postgres_data:
