version: '3.7'

services:
  web:
    build:
        context: ..
        dockerfile: config/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../source:/usr/src/app/source/
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '8001:5432'
    env_file:
      - .env

volumes:
  postgres_data: