"""
Django settings for reats project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path
from typing import Any, cast

import boto3
from dotenv import load_dotenv
from utils.get_secrets import fetch_aws_secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


if os.environ["ENV"].lower() not in ["local", "dev", "staging", "prod"]:
    raise ValueError("Invalid ENV value")

# Load dotenv file
env_file = f".env.{os.environ['ENV'].lower()}"
load_dotenv(os.path.join(BASE_DIR, env_file))


boto3.set_stream_logger(name="botocore.credentials", level=logging.ERROR)
session = boto3.session.Session()

ssm_client = boto3.client("ssm", region_name=os.getenv("AWS_REGION"))
boto3_logs_client = boto3.client("logs", region_name=os.getenv("AWS_REGION"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DEBUG"]

ALLOWED_HOSTS = os.environ["DJANGO_ALLOWED_HOSTS"].split(" ")
COOKER_APP_ORIGIN = "cooker"
CUSTOMER_APP_ORIGIN = "customer"
DELIVERY_APP_ORIGIN = "delivery"

# Application definition

INSTALLED_APPS = [
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "customer_app",
    "cooker_app",
    "delivery_app",
    "core_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "source.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "source.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

secret_data = fetch_aws_secrets(os.environ["AWS_SECRET_NAME"])
public_key = fetch_aws_secrets(os.environ["AWS_PUBLIC_KEY"], is_json=False)
private_key = fetch_aws_secrets(os.environ["AWS_PRIVATE_KEY"], is_json=False)

if secret_data:
    print("Secrets loaded successfully")

    COOKER_APP_API_KEY = secret_data["COOKER_APP_API_KEY"]
    CUSTOMER_APP_API_KEY = secret_data["CUSTOMER_APP_API_KEY"]
    DELIVERY_APP_API_KEY = secret_data["DELIVERY_APP_API_KEY"]
    GOOGLE_API_KEY = secret_data["GOOGLE_API_KEY"]
    STRIPE_PRIVATE_API_KEY = secret_data["STRIPE_PRIVATE_API_KEY"]
    STRIPE_WEBHOOK_ENDPOINT_SIGNATURE = secret_data["STRIPE_WEBHOOK_ENDPOINT_SIGNATURE"]
    SECRET_KEY = secret_data["DJANGO_SECRET_KEY"]
else:
    raise RuntimeError("Failed to load secrets from AWS Secrets Manager")

if not public_key:
    raise RuntimeError("Failed to load public key from AWS Secrets Manager")

if not private_key:
    raise RuntimeError("Failed to load private key from AWS Secrets Manager")


DATABASES = {
    "default": {
        "ENGINE": os.environ["DB_ENGINE"],
        "PORT": os.environ["DB_PORT"],
    }
}

if os.environ["ENV"] != "local":
    DATABASES["default"]["HOST"] = os.environ["RDS_HOST"]
    DATABASES["default"]["USER"] = os.environ["RDS_USER"]
    DATABASES["default"]["PASSWORD"] = secret_data["RDS_PASSWORD"]
    DATABASES["default"]["NAME"] = os.environ["RDS_DB"]
else:
    DATABASES["default"]["HOST"] = os.environ["DB_HOST"]
    DATABASES["default"]["USER"] = os.environ["POSTGRES_USER"]
    DATABASES["default"]["PASSWORD"] = os.environ["POSTGRES_PASSWORD"]
    DATABASES["default"]["NAME"] = os.environ["POSTGRES_DB"]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

PHONE_REGION = "FR"
PHONE_BLACK_LIST = ("0000000000",)  # Check if we need to add more numbers

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "utils.custom_middlewares.custom_exception_handler",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("utils.custom_permissions.UserPermission",),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Reats Cooker API",
    "DESCRIPTION": "API for Reats Cooker Application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-Api-Key",
            },
            "AppOrigin": {
                "type": "apiKey",
                "in": "header",
                "name": "App-Origin",
            },
        },
    },
    "SECURITY": [{"ApiKeyAuth": [], "BearerAuth": [], "AppOrigin": []}],
}


DEFAULT_SEARCH_COUNTRY = "France"

DEFAULT_SEARCH_RADIUS = 2  # in KM

IDLE_CANCEL_TIME_FOR_ASAP_DELIVERY = 5  # in minutes
IDLE_CANCEL_TIME_FOR_SCHEDULED_DELIVERY = 60  # in minutes
ORDER_HISTORY_LIMIT_DAYS = 730  # 2 years

# Trigram search field weights (field_name, weight)
# name is prioritized over description: results matching the dish name rank higher
DISH_SEARCH_FIELD_WEIGHTS: list[tuple[str, float]] = [
    ("name", 4.0),
    ("description", 1.0),
]

DISH_SEARCH_SIMILARITY_THRESHOLD = 0.1


DRINK_SEARCH_FIELD_WEIGHTS: list[tuple[str, float]] = [
    ("name", 4.0),
    ("description", 1.0),
]

DRINK_SEARCH_SIMILARITY_THRESHOLD = 0.1


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ALGORITHM": os.getenv("DJANGO_SIMPLE_JWT_ALGORITHM"),
    "SIGNING_KEY": private_key,
    "VERIFYING_KEY": public_key,
    "TOKEN_OBTAIN_SERIALIZER": "cookers_app.serializers.TokenObtainPairWithoutPasswordSerializer",
}

SERVICE_FEES_RATE = 0.07
DEFAULT_CURRENCY = "EUR"

ACCEPTANCE_RATE_INCREASE_VALUE = 2
ACCEPTANCE_RATE_DECREASE_VALUE = 10

propagate = True
LOGGING: dict[str, Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "aws": {
            "format": "%(asctime)s [%(levelname)-8s] %(message)s [%(pathname)s:%(lineno)d]",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "root": {
        "level": "DEBUG",  # Ensure everything is logged
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "aws",
            "level": "DEBUG",  # Capture detailed logs
        },
        "watchtower": {
            "class": "watchtower.CloudWatchLogHandler",
            "boto3_client": boto3_logs_client,
            "log_group_name": os.getenv("AWS_LOG_GROUP_NAME"),
            "level": "INFO",
            "formatter": "aws",
        },
    },
    "loggers": {
        "django": {
            "level": "DEBUG",
            "handlers": ["console", "watchtower"],
            "propagate": True,
        },
        "django.request": {
            "level": "DEBUG",
            "handlers": ["console", "watchtower"],
            "propagate": True,
        },
        "django.security": {
            "level": "DEBUG",
            "handlers": ["console", "watchtower"],
            "propagate": True,
        },
        "reats_logger": {
            "level": "DEBUG",
            "handlers": ["console", "watchtower"],
            "propagate": True,
        },
    },
}


if os.environ["ENV"] == "prod":
    cast(dict[str, Any], LOGGING["root"])["handlers"] = ["watchtower"]  # Log only to CloudWatch

if os.environ["ENV"] in ["dev", "staging"]:
    cast(dict[str, Any], LOGGING["root"])["handlers"] = [
        "console",
        "watchtower",
    ]  # Log to both in dev/staging

if os.environ["ENV"] == "local":
    propagate = False
    handlers = ["console"]
