name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ENV: "local"
      DEBUG: "1"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      RSA_PRIVATE_KEY_PATH: "/reats/dev/rsa/private/key"
      RSA_PUBLIC_KEY_PATH: "/reats/dev/rsa/public/key"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SIMPLE_JWT_ALGORITHM: "RS256"

      DB_ENGINE: "django.db.backends.postgresql_psycopg2"
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: "localhost"  # Change later if using Docker Compose
      DB_PORT: "5432"

      AWS_REGION: "eu-central-1"
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reats/requirements.txt
          pip install pre-commit pytest python-dotenv

      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: Run Tests
        run: pytest reats/tests --disable-warnings

