name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reats/requirements.txt
          pip install pre-commit pytest

      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: Run Tests
        run: pytest reats/tests --disable-warnings

