name: PR CI/CD

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: 'reats_local_db'
          POSTGRES_USER: 'dev'
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: 'reats-dev-bucket'
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_ENGINE: 'django.db.backends.postgresql'
      ENV: "local"
      DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SIMPLE_JWT_ALGORITHM: 'RS256'
      POSTGRES_DB: 'reats_local_db'
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'devpassword'
      AWS_PINPOINT_ALLOWED_ATTEMPTS: 3
      AWS_PINPOINT_APP_ID: ${{ secrets.AWS_PINPOINT_APP_ID }}
      AWS_PINPOINT_BRAND_NAME: "REATS"
      AWS_PINPOINT_CHANNEL: "SMS"
      AWS_PINPOINT_CODE_LENGTH: 6
      AWS_PINPOINT_LANGUAGE: "fr-FR"
      AWS_PINPOINT_VALIDITY_PERIOD: 30
      AWS_SENDER_ID: "REATS-DEV"
      AWS_LOG_GROUP_NAME: "reats-dev"
      AWS_SECRET_NAME: ${{ secrets.AWS_SECRET_NAME }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reats/requirements.txt
          pip install pre-commit pytest python-dotenv

      - name: Wait for PostgreSQL to be Ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..30}; do
            nc -z localhost 5432 && echo "PostgreSQL is up" && exit 0
            sleep 1
          done
          echo "PostgreSQL failed to start" && exit 1

      - name: Run Migrations
        run: python reats/manage.py migrate

      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: Run Tests
        run: pytest reats/tests --disable-warnings
